apropos page done
WildCodeSchool-2024-02/LILLE-0224-P3-G1-originsdigital pull request #2
Opened 2024-06-11 12:00 UTC by zhdanove59

2024-06-11 12:23 UTC, alexoualexandre approved these changes

2024-06-13 09:48 UTC, fantinerudent requested changes
👏🏻👏🏻
juste peux-tu mettre les composants en anglais : about (et non à propos) et le nom des class css en anglais!

2024-06-13 13:46 UTC, fantinerudent approved these changes

2024-06-13 14:45 UTC, alexoualexandre approved these changes
pareil ,fait un effort aussi ,c'est bof bof

2024-06-20 14:36 UTC, merged