Contact page, informations,questions,terms of use Done
WildCodeSchool-2024-02/LILLE-0224-P3-G1-originsdigital pull request #4
Opened 2024-06-13 12:57 UTC by zhdanove59

2024-06-14 07:03 UTC, alexoualexandre approved these changes

2024-06-14 08:01 UTC, fantinerudent requested changes

2024-06-14 08:01 UTC, fantinerudent commented on client/src/main.jsx
> +        element: <ConditionsDutilisation />,
les noms de composants en anglais svp

2024-06-14 08:01 UTC, fantinerudent commented on server/jest.config.js
> +  // container-bodynvironment: "jest-environment-node",
je ne comprend pas pourquoi ce fichier a été modifié?

2024-06-17 07:29 UTC, zhdanove59 commented on client/src/main.jsx
> +        element: <ConditionsDutilisation />,
C'est fait :D

2024-06-17 07:30 UTC, zhdanove59 commented on server/jest.config.js
> +  // container-bodynvironment: "jest-environment-node",
Je sais pas non plus mais je dirais a cause du package que j'ai installer email.js !

2024-06-17 10:19 UTC, fantinerudent requested changes
... beaucoup de code mort et de franglais...

2024-06-17 10:19 UTC, fantinerudent commented on client/src/components/Contact/ConditionsDutilisation.jsx
> +export default function ConditionsDutilisation() {
english

2024-06-17 10:19 UTC, fantinerudent commented on client/src/components/Contact/ContactPage.css
> +  /*background-image: url(../../assets/images/contactez-nous.jpg);
code mort

2024-06-17 10:19 UTC, fantinerudent commented on client/src/components/Contact/InfoContact.css
> +  /*width: 10%;*/
code mort....

2024-06-17 15:02 UTC, fantinerudent approved these changes

2024-06-17 15:11 UTC, merged