header ok
WildCodeSchool-2024-02/LILLE-0224-P3-G1-originsdigital pull request #5
Opened 2024-06-13 14:42 UTC by alexoualexandre

2024-06-13 14:44 UTC, zhdanove59 approved these changes
Faire un effort la prochaine fois stp
Cordialement

2024-06-14 08:03 UTC, fantinerudent requested changes

2024-06-14 08:03 UTC, fantinerudent commented on client/src/App.jsx
> +// import { Outlet } from "react-router-dom";
code mort / doublon

2024-06-14 08:03 UTC, fantinerudent commented on client/src/components/Header/header.jsx
> +  // const {style, setStyle,defile, setDefile,searchbar, setSearchBar,onBlur, setOnBlur} = moncontext();
ce composant est en travaux ?

2024-06-14 10:47 UTC, fantinerudent approved these changes

2024-06-14 11:14 UTC, merged