Us0 video player description
WildCodeSchool-2024-02/LILLE-0224-P3-G1-originsdigital pull request #7
Opened 2024-06-14 06:46 UTC by MontandonArnauld

Add description of the video on top of the player

2024-06-14 07:02 UTC, alexoualexandre approved these changes

2024-06-14 08:06 UTC, fantinerudent requested changes

2024-06-14 08:06 UTC, fantinerudent commented on client/src/components/VideoplayerDescrirption/VideoplayerDescription.jsx
> +              <h2 className="title_genre">FILM PAR GENRES</h2>
FilmS par genre

2024-06-14 08:06 UTC, fantinerudent commented on client/src/components/VideoplayerDescrirption/VideoplayerDescription.jsx
> +        {/* <div className="videoplayer_description_vignette"> */}
code mort

2024-06-18 14:37 UTC, fantinerudent approved these changes

2024-06-18 15:26 UTC, fantinerudent approved these changes

2024-06-20 12:03 UTC, merged